CYP51_F <- "ACAGGATGTCGTCTGGATAGTTAAGGTA"
CYP51_R <- "TCTTCCCCAGACCAAATTATCGTTCGA"

CYTB_F <- "ATGTCAATAGGCATGCAACCGT"
CYTB_R <- "ATACATAGATCATGTAACTATA"

MFS_F <- "GGAGCGGAGCGGGACGAATCGAGA"
MFS_R <- "GAGGCCAGTCGAGGCTTTTACATA"