CYP51_F <- "ACAGGATGTCGTCTGGATAGTTAAGGTA"
CYP51_R <- "TCTTCCCCAGACCAAATTATCGTTCGA"

CYTB_R <- "ATACATAGATCATGTAACTATA"
CYTB_F <- "ATGTCAATAGGCATGCAACCGT"


MFS_F <- "GGAGCGGAGCGGGACGAATCGAGA"
MFS_R <- "GAGGCCAGTCGAGGCTTTTACATA"