CYP51_F <- "GCACGTGGGTAGAGGGTTAT"
CYP51_R <- "CAGGTGGAGTTTGCATAGGG"

CYTB_F <- "ATGTCAATAGGCATGCAACCGT"
CYTB_R <- "ATACATAGATCATGTAACTATA"

MFS_F <- "GGAGCGGAGCGGGACGAATCGAGA"
MFS_R <- "GAGGCCAGTCGAGGCTTTTACATA"